"""
AI Service — Singleton wrapper around the Agent class.

Design decisions:
  - The Agent is loaded exactly **once** via ``AIService.initialize()``,
    called during the FastAPI lifespan startup event.
  - ``chat()`` delegates to ``starlette.concurrency.run_in_threadpool``
    so the synchronous, CPU-heavy ``Agent.chat()`` never blocks the
    async event loop.
  - All Agent-originating exceptions are caught and re-raised as
    ``AIServiceError`` with appropriate error codes.
"""

import logging
import sys
from pathlib import Path
from typing import Any

from starlette.concurrency import run_in_threadpool

from app.core.errors import AIServiceError, ErrorCode

logger: logging.Logger = logging.getLogger(__name__)

# ── Ensure the project root is on sys.path so ``import chat`` resolves ──
_project_root: str = str(Path(__file__).resolve().parents[2])
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)


class AIService:
    """Singleton service that wraps the Agent from ``chat.py``."""

    _instance: "AIService | None" = None
    _agent: Any = None  # chat.Agent instance

    # ── Lifecycle ────────────────────────────────────────────────

    @classmethod
    def initialize(cls) -> "AIService":
        """Instantiate the Agent exactly once.

        Must be called during server startup (lifespan).
        This is a **blocking** operation — the caller is responsible
        for running it inside ``run_in_threadpool`` if needed.
        """
        if cls._instance is not None:
            logger.warning("AIService.initialize() called more than once — skipping.")
            return cls._instance

        logger.info("Loading AI Agent (this may take a while)…")
        try:
            from chat import Agent  # type: ignore[import-untyped]

            instance = cls()
            instance._agent = Agent()
            cls._instance = instance
            logger.info("AI Agent loaded successfully.")
            return instance
        except MemoryError as exc:
            raise AIServiceError(
                message="Out of memory while loading the AI model.",
                code=ErrorCode.AI_OUT_OF_MEMORY,
                original_error=exc,
            ) from exc
        except Exception as exc:
            raise AIServiceError(
                message=f"Failed to initialize AI Agent: {exc}",
                code=ErrorCode.AI_GENERIC,
                original_error=exc,
            ) from exc

    @classmethod
    def get_instance(cls) -> "AIService":
        """Return the singleton.  Raises ``RuntimeError`` if not yet initialised."""
        if cls._instance is None:
            raise RuntimeError(
                "AIService has not been initialised. "
                "Call AIService.initialize() during server startup."
            )
        return cls._instance

    # ── Public API ───────────────────────────────────────────────

    async def chat(self, query: str) -> str:
        """Send a query to the AI Agent and return its text response.

        Wraps the blocking ``Agent.chat()`` in a threadpool so the
        FastAPI event loop stays responsive.

        Returns:
            The plain-text answer generated by the LLM.

        Raises:
            AIServiceError: on timeout, OOM, or any unexpected failure.
        """
        try:
            result = await run_in_threadpool(self._agent.chat, query)
        except TimeoutError as exc:
            raise AIServiceError(
                message="AI query timed out.",
                code=ErrorCode.AI_TIMEOUT,
                original_error=exc,
            ) from exc
        except MemoryError as exc:
            raise AIServiceError(
                message="Out of memory during AI query.",
                code=ErrorCode.AI_OUT_OF_MEMORY,
                original_error=exc,
            ) from exc
        except Exception as exc:
            raise AIServiceError(
                message=f"AI query failed: {exc}",
                code=ErrorCode.AI_GENERIC,
                original_error=exc,
            ) from exc

        # Agent.chat() now returns a plain text string from the LLM
        if not isinstance(result, str):
            result = str(result)

        return result
